### ISSUE TITLE
useWebWalletTxSend not loading txResult due to useEffect not using dependencies (race condition)

### ISSUE THREAD

**Issue by AlissonRS** [useElven/core#4] opened 2023-05-04 02:33 UTC
Hello!

After signing a transaction, we are supposed to get the `txResult` and a few other state from `useTransaction` are supposed to be populated via the `useWebWalletTxSend`. I noticed sometimes this randomly doesn't happen because of the piece of code below:

```
    if (
      walletProviderStatus === WALLET_PROVIDER_CALLBACK_PARAM_TX_SIGNED &&
      networkStateSnap.apiNetworkProvider &&
      networkStateSnap.dappProvider
    ) {
      send();
    }
```

This runs inside a `useEffect`, which somehow runs before the `networkStateSnap.apiNetworkProvider` is set, and because the `useEffect` doesn't add it as a dependency, it won't run again. I can see even the eslint rule to warn about this is disabled for this line.

This can be fixed at the frontend level, by making sure whatever components call `useTransaction` only get mounted after the `networkStateSnap` is fully loaded (e.g. inside the `<Authenticated>` HOC), but something that can catch devs off-guard (like me).

In order to provide a better DX, ideally disabling eslint rules should be avoided and `useEffect` fixed to work as it should, by adding all dependencies required by the code, though I can see a problem with the `cb` (callback function) which can be passed down from the frontend dapp without a `useCallback` (thus forcing the `useEffect` to re-execute every time).

A workaround for now is to throw an exception (or log a warning on console for devs) in case the `networkStateSnap` is not loaded yet, at least until a better solution can be thought of:

```
    if (!networkStateSnap.apiNetworkProvider || !networkStateSnap.dappProvider)
      throw new Error("Network State not loaded. Make sure you call useTransaction inside the <Authenticated> component.");

    if (walletProviderStatus === WALLET_PROVIDER_CALLBACK_PARAM_TX_SIGNED)
      send();
```

I could help with a PR, let me know your thoughts!

**Comment by juliancwirko** [comment] 2023-05-04 07:55
Hi, thanks for your feedback. I am unsure if I understood your use case correctly, but this hook aims to trigger only once, and it assumes that the network providers should be initialized and you are in an 'authenticated context'. But it is specific because it relays on page load, so there may be a problem. I would need to check. Do you have a small reproduction repository for that? Is it only because you use `useTransaction` outside of the authenticated context?

Generally, not all dependencies are always required in useEffect. For example, the cb function here, but maybe it would be good to rely on the 'dapp and network provider' here. I'm not sure yet. I haven't found any problems using it, but I can imagine it now. So reproduction repository would be helpful :pray: 

And yes, the general rule I had in mind was to not wrap the whole app with auth provider and force users to wait for the authentication state to resolve (this has some implications, for example, in Next.js apps). It can be done using the `Authenticated` component in the parts of code where it is required or with custom checks (components) using hooks. But it probably needs better DX. For example, something like throwing errors with a good message, as you mentioned.

I'll take a look. I'll think about how to make it more predictable. Maybe the web wallet 'tx send' logic could also be extracted to a separate hook/tool and then used by developers separately.

**Comment by juliancwirko** [comment] 2023-05-06 18:49
In v0.3.0, I added useEffect dependencies and the information about the necessity to use it in the signed-in context in the docs.
It will probably be refactored more in the future.
I'll close it for now, but feel free to comment.

**Closed as completed by juliancwirko** 2023-05-06 18:49 UTC
